name: PikaOS Package Dev build (Nvidia Ubuntu Forced 555)

on:
  push

jobs:
  build:
    strategy:
      matrix:
        pika-image:
          - pika-package-container
          - pika-i386-package-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/${{ matrix.pika-image }}:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update apt cache
      run: apt-get update -y
    
    - name: Build amd64 Package
      run: ./ubuntu-nvidia-drivers-mirror/makedriver.sh amd64
    
    - name: Prepare nVidia driver archive
      run: ./prep-archives.sh
    
    - name: See for ourselves
      run: ./check-files.sh
